inventory/service/group_vars/graphite.yaml, inventory/service/groups.yaml, playbooks/roles/graphite/defaults/main.yaml, playbooks/roles/graphite/tasks/main.yaml, playbooks/roles/graphite/templates/env.j2, playbooks/roles/graphite/templates/graphite-statsd.conf.j2, playbooks/roles/graphite/templates/graphite.service.j2, playbooks/service-graphite.yaml, playbooks/templates/graphite/carbonate.conf.j2, playbooks/templates/graphite/graphite_list_foreign_metrics.sh.j2, playbooks/templates/graphite/graphite_resync_node.sh.j2, playbooks/zuul/templates/group_vars/graphite.yaml.j2, testinfra/test_graphite.py, zuul.d/system-config-run.yaml
- slight change in graphite configs
- fallback to using root for graphite
- Graphite container doesn't really want to be running as non root container with tons of problems. Let's run it as root, but add a separate user for sync
=> Fallback to use root for graphite

playbooks/templates/grafana/apimon/_kpi_compute.yaml.j2, playbooks/templates/grafana/apimon/compute.yaml.j2, zuul.d/infra-prod.yaml, zuul.d/project.yaml
When selecting multiple zones server provisioning duration was summed
and not averaged.
While being on that enable automatic deployment of dashboards in deploy
pipeline.
=> Fix compute dashboard

inventory/service/groups.yaml, playbooks/acme-certs.yaml, playbooks/service-alerta.yaml, playbooks/service-apimon-epmon.yaml, playbooks/service-apimon-executor.yaml, playbooks/service-apimon-scheduler.yaml, playbooks/service-bridge.yaml, playbooks/service-grafana.yaml, playbooks/service-graphite.yaml, playbooks/service-memcached.yaml, playbooks/service-proxy.yaml, playbooks/service-statsd.yaml, playbooks/set-hostnames.yaml, playbooks/x509-certs.yaml
Since we start supporting ssh not as root we need to consistently
elevate privileges (become root) in most of the playbooks where it is
necessary.
=> Add privilege elevation to most playbooks

playbooks/roles/base/server/tasks/main.yaml
- fix wrong parameter name in the fallback package installations
- enable compression of the logrotate logs to try to use less space
=> Fix base role

inventory/base/group_vars/all.yaml, inventory/service/group_vars/otc.yaml, inventory/service/groups.yaml, playbooks/roles/base/unbound/tasks/main.yaml, playbooks/roles/base/unbound/templates/unbound.confd.conf.j2
Add unbound forward-zone support and add some OTC located hosts which
need to use internal DNS resolution rather then public one.
=> Unbound forward-zone support

inventory/service/group_vars/proxy.yaml, playbooks/roles/haproxy/templates/haproxy.cfg.j2
- k8 deployed apps (on same fqdn) might require tricks (senf host header
for carbonapi healthcheck)
- generalize backend options
=> Optimize haproxy config

playbooks/roles/base/server/defaults/main.yaml, playbooks/roles/base/server/tasks/main.yaml
set maxsize in logrotate options (default 300M)
=> Limit maximal log file size

inventory/service/group_vars/proxy.yaml, playbooks/roles/haproxy/defaults/main.yaml, playbooks/roles/haproxy/templates/haproxy.cfg.j2, playbooks/roles/haproxy/templates/haproxy.service.j2, playbooks/zuul/templates/gate-groups.yaml.j2, testinfra/test_proxy.py, zuul.d/system-config-run.yaml
Some last changes in inventory were causing proxy service failure. Jobs
are not being executed on changes only in inventory.
Change of the image  (2.3=>2.4) brings new required changes into the role, incorporate them.
=> Test proxy changes in inventory

inventory/service/group_vars/database-launcher.yaml, inventory/service/group_vars/proxy.yaml, inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/proxy1.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/proxy2.eco.tsi-dev.otc-service.com.yaml, playbooks/roles/db_pg/tasks/db.yaml
atm matrix server is provisioned manually, but at least we can add it
under proxy config and request ssl certs properly.
=> Add initial matrix config

inventory/service/group_vars/grafana.yaml
New grafana including hotfix is released. Same is for
grafana-image-renderer. Start using them.
Images are mirrored to regular location.
=> Update Grafana to 8.0.1

inventory/service/group_vars/cloud-launcher.yaml, inventory/service/group_vars/zuul.yaml, inventory/service/groups.yaml, playbooks/cloud-identity.yaml, playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml, playbooks/roles/zuul_k8s/tasks/zuul-web.yaml, playbooks/roles/zuul_k8s/templates/zuul.conf.j2, playbooks/templates/clouds/bridge_all_clouds.yaml.j2, playbooks/templates/clouds/bridge_kube_config.yaml.j2, playbooks/zuul/templates/group_vars/control-plane-clouds.yaml.j2, playbooks/zuul/templates/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml.j2
in order to automate Zuul infra we need to redeploy VPC, CCE. Provision
this infra now properly and on the way change to zuul.otc-service.com
domain upgrading to Zuul 4.6.0
=> Redeploy zuul infra

playbooks/dashboards.yaml, playbooks/templates/grafana/apimon/_kpi_block_storage.yaml.j2, playbooks/templates/grafana/apimon/_kpi_cce.yaml.j2, playbooks/templates/grafana/apimon/_kpi_image.yaml.j2, playbooks/templates/grafana/apimon/_template_env.yaml.j2, playbooks/templates/grafana/apimon/_template_zone.yaml.j2, playbooks/templates/grafana/apimon/endpoint_monitor.yaml.j2, playbooks/templates/grafana/apimon/kpi.yaml.j2, playbooks/templates/grafana/apimon/macros.j2
some finetuning of the dashboards to work well with carbonapi. Reverse
compatibility is not guaranteed, therefore merging this asumes switching
generally to carbonapi.
graphiteweb app remains.
=> Fix dashboards for carbonapi

inventory/service/group_vars/proxy.yaml
Sometimes we see haproxy crashes. 2.4.1 fixed some potential crashes.
Update to see whether it helps us.
=> Switch to haproxy 2.4.1

inventory/service/host_vars/graphite1.apimon.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/graphite1.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/graphite2.apimon.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/graphite3.apimon.eco.tsi-dev.otc-service.com.yaml
we have a fallback for carbonapi to be served by graphite instances, but
firewall is currently blocking required port.
=> Enable carbonapi port on graphite instances

inventory/service/host_vars/proxy1.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/proxy2.eco.tsi-dev.otc-service.com.yaml
apimon.eco.tsi-dev.otc-service.com is a zone and does not really require
SSL cert. Drop it since playbook fails to get cert for it
=> Remove host from ssl inventory

playbooks/templates/grafana/apimon/endpoint_monitor.yaml.j2
endpoint monitoring dashboard on the nl@de env fails. This is caused by
something in the carbonapi, since switching back DS manually fixes the
situation. Until we figure out what is wrong - force DS for this panel
to be "apimon".
=> Fallback to apimon DS for endpoint dashboard

playbooks/roles/zuul_k8s/tasks/main.yaml, playbooks/roles/zuul_k8s/tasks/nodepool.yaml, playbooks/roles/zuul_k8s/tasks/statsd.yaml, playbooks/roles/zuul_k8s/tasks/zuul-scheduler.yaml, playbooks/roles/zuul_k8s/tasks/zuul.yaml, playbooks/service-zuul-k8s.yaml
In order to be able to only refresh zuul confguration add "config" tag
to multiple tasks of the zuul deployment. invoking it with
`ansible-playbook playbooks/service-zuul-k8s.yaml --tags config` only
updates configs.
=> Add tags into zuul playbooks/role

playbooks/roles/haproxy_monitor/tasks/main.yaml
from logs we see reload happens, but it is not able to recover when all
backends are down.
=> reload apprantly does not rescue from haproxy down backends

playbooks/roles/carbonapi/templates/carbonapi-healthcheck.sh.j2
Changed parameter for curl to use -m , maximum time for whole operation to take before exit.
With --connect-timeout there are cases where tcp port is open, but application does not respond and curl hangs.
=> changed curl parameter to -m

zuul.d/project.yaml
manage-git job has old files definition which is not triggering job at
all.
=> Fix git job affected files

playbooks/roles/base/server/tasks/main.yaml
Due to the fact, that in logrotate order of config files matters -
ensure our file is the first one.
=> rename sysconfig logrotate conf file

playbooks/roles/haproxy/templates/haproxy.cfg.j2
Use
https://ssl-config.mozilla.org/#server=haproxy&version=2.1&config=modern&openssl=1.1.1d&guideline=5.6
to configure our haproxy in the best secure way.
=> Adapt SSL setting of haproxy

playbooks/roles/base/server/tasks/main.yaml
- ensures logrotate.timer is running
- adding ignore_errors for distros which do not use timer service for logrotate like Centos 8
=> logrotate update

playbooks/zuul/run-production-playbook.yaml
It was already done in the base-jobs playbook. Adding host is still
required.
=> Remove readding bridge key.

playbooks/zuul/run-production-playbook.yaml
The dependent change moves this into the common infra-prod-base job so
we don't have to do this in here.
=> infra-prod: remove master override steps

inventory/base/hosts.yaml
In order to stop using root login from bridge to hosts we introduce
automation user. It will be the only possibility for bridge to connect
to the host (system admins of course are still able to connect).
Once this is done we can disable root ssh login as required by security
regulations.
=> Switch login to hosts to 'automation' user

inventory/base/hosts.yaml
Deploy new FCOS to replace existing executor2. It is deployed with the
ignition file providing desired disk setup.
=> Replace executor2 host

playbooks/acme-certs.yaml
Since we provision clouds creds to root we also need to become root for
using those creds. Until we learn playbook to get vals from vault - just
use root.
=> become root for dns management

playbooks/roles/base/server/defaults/main.yaml
some of our OSs are not supporting SK hostkeytypes. Disable them for now
until we find a better solution
=> Temporarily disable some SSH HostKeyTypes

zuul.d/infra-prod.yaml, zuul.d/project.yaml, zuul.d/system-config-run.yaml
last commit renamed install-ansible job/playbook to boostrap-bridge, but
the job still tried to use old playbook name. Fix this and add playbook
to the system-run job filters.
=> Fix bootstrap-bridge job

playbooks/roles/zuul_k8s/tasks/zuul-client.yaml, playbooks/roles/zuul_k8s/tasks/zuul.yaml
We might need to have a standalone zuul client to do some maintenance
(i.e. it is required to clean ZK state while doing update to 4.11 while
zuul itself is down). Since we are moving slowly to having zk in the k8
itself we can only reasonably have zuul client in the same k8 (for case
when zk is not accessible from outside).
=> Add zuul-client k8 deployment

inventory/service/groups.yaml, playbooks/grafana-datasources.yaml, playbooks/roles/grafana/tasks/import_ds.yaml, playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml, zuul.d/infra-prod.yaml, zuul.d/project.yaml
Implement management of the grafana datasources:
- add grafana-controller group (with bridge in it) from where playbook
is executed
- datasources are configured in the secret part of the inventory
- job is executed periodically to ensure secrets rotation
=> Add grafana-datasources job

playbooks/bootstrap-bridge.yaml, playbooks/roles/hashivault/vars/Debian.yaml
we need to ensure that even if sc2 is not checked out ansible will
be able to run.
=> Ensure inventory of the sc2 exists

playbooks/roles/configure-kubectl/tasks/main.yaml
Some tools complain over too open mode of the kube config file. Do it
600.
=> make k8 config not group readable

inventory/service/group_vars/grafana.yaml, inventory/service/host_vars/web3.eco.tsi-dev.otc-service.com.yaml, playbooks/dashboards.yaml, playbooks/roles/grafana/defaults/main.yml, playbooks/roles/grafana/tasks/import_ds.yaml, playbooks/roles/grafana/tasks/k8s.yaml, playbooks/roles/grafana/tasks/main.yml, playbooks/roles/grafana/templates/env.j2, playbooks/roles/grafana/templates/grafana-deployment.yaml.j2, playbooks/roles/grafana/templates/grafana-renderer.service.j2, playbooks/roles/grafana/templates/grafana-secret.yaml.j2, playbooks/roles/grafana/templates/grafana.service.j2, playbooks/service-grafana.yaml, playbooks/templates/grafana/ldap.toml.j2, playbooks/zuul/templates/group_vars/grafana.yaml.j2
Apply same inventory style for grafana as for other services: 1 instance
represent whole "cluster/service". To address necessity to override
installation vars add support for extra_vars which behave similar to
host_vars.
=> Restructure grafana inventory

inventory/service/group_vars/grafana.yaml, playbooks/service-grafana.yaml
Last PR accidentially tried to get extra vars using wrong var name.
=> Fix wrong extra vars variable name in grafana

playbooks/roles/install-ansible/tasks/main.yaml
K8 modules are not really depending on openshift lib anymore, instead
they use kubernetes python lib. Now even installing openshift started
failing, therefore let's get rid of it.
=> Stop installing openshift python lib to bridge

inventory/service/group_vars/apimon.yaml
smtp servers are not reachable from outside OTC - no need to deploy it there
=> drop smtp cloudmon plugin in vc

playbooks/roles/x509_vault/tasks/cert.yaml
in the x509 role we need to pass csv list alt_names into the api.
=> React properly when alt_names is list or nothing

playbooks/service-zookeeper.yaml, zuul.d/project.yaml
currently we do not have ZK on VMs. Empty host list is causing in some
areas issues with inventory plugins. For now disable ZK installation on
VMs and exclude testing jobs until further notice.
=> Temp disable ZK vm installation tasks

inventory/service/host_vars/graphite1.eco.tsi-dev.otc-service.com.yaml
If we set storage-schemas for graphite it is expected we set full schema
definition and not only some part of it. Add missing parts now.
=> set graphite.eco storage-schemas properly

inventory/service/host_vars/graphite1.eco.tsi-dev.otc-service.com.yaml
lower precision must be longer then higher precision (3m is 3 minutes, and not 3 months)
=> fix final typo in graphite storage schema definition

playbooks/roles/zookeeper/tasks/k8s.yaml
We might want to access ZK using cluster address (i.e. by zuul client
not running in the cluster to make data backup). Do not introduce
ingress, but at least make cluster IP available.
=> Make Zookeeper@k8 available outside

inventory/service/host_vars/vault1.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/vault2.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/vault3.eco.tsi-dev.otc-service.com.yaml, playbooks/roles/hashivault/templates/vault.hcl.j2
Follow the
https://support.hashicorp.com/hc/en-us/articles/115015659767-PROXY-Protocol-Support
and authorize our haproxy instances in vault config to hopefully
properly log real client ip address instead of proxy IP.
=> Enable proxy support in vault

inventory/service/host_vars/vault1.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/vault2.eco.tsi-dev.otc-service.com.yaml, inventory/service/host_vars/vault3.eco.tsi-dev.otc-service.com.yaml, playbooks/roles/hashivault/templates/vault.hcl.j2
In the L7 load balancing mode (i.e. behind haproxy with http protocol) we use not the proxy protocol, but X_Forwarded_For headers. Vault is having special config vars for this also.
=> ensure clientIP for vault is shown in L7 LB

playbooks/roles/zuul_k8s/tasks/nodepool.yaml
Some OS in dib rely on podman, which fails when it does not have real FS
(https://opendev.org/opendev/system-config/src/branch/master/playbooks/roles/nodepool-builder/templates/docker-compose.yaml.j2)
Try to do same and add emptyDir.
=> Attach /var/lib/containers in nodepool-builder

inventory/service/group_vars/zuul.yaml
since nodepool is still not having release use current latest as
post5.0.0. This is required to get a newer diskimage-builder with some
important fixes.
=> Update zuul nodepool

zuul.d/infra-prod.yaml
When we modify zuul inventory there is no need to run all other
playbooks. While our inventories are still tightly coupled we can skip
it by placing zuul inv file to irrelevant-files of the base job.
=> Skip deploy jobs for zuul inventory change

inventory/service/group_vars/zuul.yaml, playbooks/roles/zuul_k8s/tasks/nodepool.yaml, playbooks/roles/zuul_k8s/tasks/zuul-executor.yaml, playbooks/roles/zuul_k8s/tasks/zuul-merger.yaml, playbooks/roles/zuul_k8s/tasks/zuul-scheduler.yaml, playbooks/roles/zuul_k8s/tasks/zuul-web.yaml
As a preparation for deploying backup zuul we should make cluster setup
configurable. For now only cover current cluster.
=> Make zuul instance counts configurable

playbooks/roles/graphite/defaults/main.yaml
We sadly need to keep 1m precision during one month. Make this now
become default.
=> Change default graphite retentions

inventory/service/group_vars/graphite.yaml
Reduce precision for telegraf metrics in graphite. Since this requires
adding new section to storage-schemas we move definitions to inventory.
=> Differentiate graphite storage schema for telegraf

playbooks/grafana-datasources.yaml, playbooks/roles/grafana/tasks/import_ds.yaml
When we want to get Grafana datasource credentials from vault we were
relying on vault lookup plugins in the inventory. While it is good on
its own it causes getting new vars every time inventory gets evaluated.
In addition if we are not accurate we get user and password not even
matching together.
Instead let us read creds from vault if vault_path is set for the DS.
=> Fix grafana DS creds management

playbooks/templates/docs_hosting/nginx-internal.conf.j2
- set back to http for backend
- temporarily set default container to docs from docsportal unless we
create one (otherwise ready checks fail)
=> Fix docs-int template

playbooks/roles/cloud_cce/tasks/main.yaml, playbooks/roles/cloud_host/tasks/main.yaml, playbooks/roles/cloud_natgw/tasks/main.yaml, playbooks/roles/cloud_net/tasks/destroy.yaml, playbooks/roles/cloud_net/tasks/main.yaml, playbooks/roles/cloud_net/tasks/net.yaml, playbooks/roles/cloud_net/tasks/provision.yaml, playbooks/roles/cloud_rds/tasks/main.yaml, playbooks/roles/cloud_sg/tasks/main.yaml, playbooks/roles/cloud_vpcp/tasks/main.yaml, playbooks/roles/install-docker/tasks/main.yaml
Minor fix to avoid deprecation message
```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
=> Replaced include to include_tasks

zuul.d/infra-prod.yaml, zuul.d/system-config-run.yaml
default branch of the ansible-colleciton-cloud has been renamed to "main"
=> rename branch of the ansible-collection-cloud

inventory/service/group_vars/cloud-launcher.yaml
Deploying first resources into the projects is currently commented out, since we first need to have projects deployed, then manage cloud connections and afterwards we can start provisioning
=> add failover projects

inventory/service/group_vars/gitea.yaml, playbooks/roles/gitea/templates/app.ini.j2
sadly we are not able to rollback without downgrading DB what we are not able to do. In order to at least somehow let people work increase default amount of files in diff to 500 files.
=> Workaround gitea bug with showmore button

playbooks/roles/gitea/templates/app.ini.j2
We should disable exposing our users to the outside world (google)
Config options uses as described in https://docs.gitea.io/en-us/config-cheat-sheet
=> disable listing users in gitea without auth

playbooks/roles/gitea/templates/app.ini.j2
- unset require_signing_view since otherwise not possible to have public orgs/repos
- set default org visibility to limited to reduce change of accidential exposing of hidden repos
- set DEFAULT_KEEP_EMAIL_PRIVATE to true
=> rework gitea default permissions

playbooks/templates/docs_hosting/redirect_maps/redirect-elastic-cloud-server.map
https://github.com/opentelekomcloud-docs/docsportal/issues/59
Since the link on it's own is broken we redirect rewrite it to general
key pair page.
=> Add a redirect for broken link

playbooks/templates/docs_hosting/nginx-beta.conf.j2, playbooks/templates/docs_hosting/nginx-public.conf.j2
nginx-public template is used for "main" docs portal as well and this on
is not having any redirect maps. Since we evaluate result of this map in
a general block it makes sence to move it outside of the if.
=> Move map statement outside of jinja if

kubernetes/zuul/base/kustomization.yaml, kubernetes/zuul/components/nodepool-builder/statefulset.yaml, kubernetes/zuul/components/nodepool-launcher/deployment.yaml, kubernetes/zuul/components/nodepool-launcher/hpa.yaml, kubernetes/zuul/components/nodepool-launcher/kustomization.yaml, kubernetes/zuul/components/restarter/README.md, kubernetes/zuul/components/restarter/crb.yaml, kubernetes/zuul/components/restarter/job-restart-nodepool-launcher.yaml, kubernetes/zuul/components/restarter/job-restart-zuul-web.yaml, kubernetes/zuul/components/restarter/kustomization.yaml, kubernetes/zuul/components/restarter/role.yaml, kubernetes/zuul/components/restarter/sa.yaml, kubernetes/zuul/components/zookeeper/kustomization.yaml, kubernetes/zuul/components/zookeeper/statefulset.yaml, kubernetes/zuul/components/zuul-client/deployment.yaml, kubernetes/zuul/components/zuul-config/deployment.yaml, kubernetes/zuul/components/zuul-executor/statefulset.yaml, kubernetes/zuul/components/zuul-merger/deployment.yaml, kubernetes/zuul/components/zuul-merger/hpa.yaml, kubernetes/zuul/components/zuul-merger/kustomization.yaml, kubernetes/zuul/components/zuul-scheduler/statefulset.yaml, kubernetes/zuul/components/zuul-web/deployment.yaml, kubernetes/zuul/overlays/zuul_ci/configs/site-vars.yaml, kubernetes/zuul/overlays/zuul_ci/configs/vault-agent/executor-base-vault-agent.hcl, kubernetes/zuul/overlays/zuul_ci/crb_admin.yaml, kubernetes/zuul/overlays/zuul_ci/kustomization.yaml, kubernetes/zuul/overlays/zuul_ci/patch-nodepool.yaml, kubernetes/zuul/overlays/zuul_ci/patch-zuul-executor.yaml, kubernetes/zuul/overlays/zuul_ci/patch-zuul.yaml
in order of a switch to the new setup few issues have been identified
- missing vault base token and vars inside zuul executor
- too high requests for most components
- updated nodepool to 8.2.0
- added cronjobs to restart zuul-web and nodepool-launcher
- add nodepool-launcher hpa
- converted zuul-merger from SS to Dpl
- enabled vault un-templating for zuul-client/config
- simplified overlay kustomization patching
- fixed patchong of nodepool-launcher
- update zookeeper to 3.8.1 with few interesting bugfixes
=> feat: update Zuul Kustomize app

playbooks/zuul/run-production-playbook-post.yaml
when fetching encrypted logs we started seeing issue with keeping attrs
after zuul migration. Ownership is anyway not what we need so we can
safely skip that.
=> fix: do not try to preserve log ownership

inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
in one of last changes we started forcing ansible to use
/usr/ansible-venv python interpreter. This causes inability to use
certain system-only packages (firewalld). Instead other jobs would need
to be extended with installing dependent packages no into the venv
=> fix: stop forcing ansible python path on bridge

kubernetes/swift-proxy/base/kustomization.yaml
Set the version explicitly, since tag "latest" has been removed from dockerhub
=> Set vault tag explicitly for siwft-proxy app

kubernetes/swift-proxy/base/kustomization.yaml, kubernetes/swift-proxy/overlays/helpcenter_internal/kustomization.yaml, kubernetes/swift-proxy/overlays/helpcenter_internal_swiss/kustomization.yaml
since vault container is not used in the base layer it makes no impact
at all. Instead we should define it in the overlay that really require
it.
=> Better fix vault image

doc/requirements.txt, tox.ini
hacking! is pulling flake==2.5.5 which is not working with py311. Fix
this by updating to the much much newer version (with package rename) to
6.0.1.
=> update hacking version

inventory/service/group_vars/k8s-controller.yaml
8.4.0 is latest available version for prometheus-blackbox-exporter
=> Update version for prometheus-blackbox-exporter helm chart 7.1.3-> 8.4.0

inventory/service/group_vars/k8s-controller.yaml
Updated to last available version; Required CRD updated to v0.68.0 version
=> Update version for kube-prometheus-stack helm chart 41.6.1 -> 51.8.1

inventory/service/group_vars/k8s-controller.yaml
Updated to the latest available helmchart loki version
=> Update version for loki helm chart 5.5.0 -> 5.34.0

playbooks/templates/charts/prometheus/prometheus-otcinfra-values.yaml.j2, playbooks/templates/charts/prometheus/prometheus-otcinfra2-values.yaml.j2
alertmanager.alertmanagerSpec
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values&path=alertmanager.alertmanagerSpec
=> Change wrong config name for alertmanagerSpec section

kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_internal/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_public/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_beta/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_internal/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_public/kustomization.yaml, playbooks/roles/document_hosting_k8s/templates/deployment.yaml.j2
The CPUThrottlingHigh is an alert created by the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project. The best practice is to remove limit for cpu.
=> Remove cpu limits for configmap-sync and redirect-configmap-sync pods

kubernetes/zuul/components/nodepool-launcher/hpa.yaml, kubernetes/zuul/components/zuul-web/hpa.yaml
It seems that HorizontalPodAutoscaler uses request (not limit) to determine when to scale by percent
=> Add additional replics for HPA zuul-web, nodepool-launcher due alerts

kubernetes/grafana-docs-monitoring/base/cronjob-scheduler.yaml
1) Change from 10:00 to 09:00 since clock on runner and zulip server are not synced, and messages comes at 11:00
=> Change run time

playbooks/roles/node-exporter/templates/node-exporter.service.j2, playbooks/roles/promtail/templates/config.yml.j2, playbooks/roles/promtail/templates/promtail.service.j2, playbooks/roles/telegraf/templates/telegraf.service.j2
Enabling collection logs for containers from VM forpromtail, telegraf, node-exporter containers;
Solving the problem of rotating docker container logs;
=> Update promtail, telegraf, node-exporter as non disruptive components

playbooks/roles/install-osc-container/files/openstack
This might be the issue of the docker image itself where it produces carriage return character at the end of line
=> removing pseudo-tty option which breaks cli output

playbooks/roles/base/audit/tasks/main.yaml
Added the `ignore_errors: true` parameter to Ansible tasks to prevent interruptions caused by errors when searching for and logging privileged commands on `base/audit` role for `infra-prod-base-ext` zuul job. 
These changes allow the playbook to continue execution even if some commands return errors related to non-existent container binaries. Examples of such errors include:
```
fatal: [executor4.apimon.eco.tsi-dev.otc-service.com]: FAILED! => {
"changed": false,
"cmd": "df --local -P | awk {'if (NR!=1) print $6'}  \\\n| xargs -I '{}' find '{}' -xdev -type f \\( -perm -4000 -o -perm -2000 \\) -print 2>/dev/null\n",
"delta": "0:00:01.915619",
"end": "2024-08-06 08:03:51.166100",
"rc": 123,
"start": "2024-08-06 08:03:49.250481"
}
```
```
failed: [graphite1.eco.tsi-dev.otc-service.com] …
```
=> Add ingnore_errors: true for Search and Configure priv commands on base/audit role

inventory/service/group_vars/k8s-controller.yaml
to fix issue with:
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "prometheus-blackbox-exporter-psp" namespace: "monitoring" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```
=> upgrade prom blackbox chart to 9.2.0

kubernetes/argocd-apps/system/kube-prometheus-stack/Chart.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-de.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-nl.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcci.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra2.yaml
- Bump kube-prometheus-stack chart version from 51.8.1 to 69.7.2
- Set serviceMonitorSelectorNilUsesHelmValues to false across multiple environments
- Remove commented-out cert-manager scrape configs
=> Upgrade kube-prometheus-stack and adjust service monitor configuration

kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-de.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-nl.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcci.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra2.yaml
Add `crds.enabled: true` configuration to kube-prometheus-stack values files for multiple environments to ensure proper CRD installation and management.
Environments updated:
- cloudmon-de
- cloudmon-nl
- otcci
- otcinfra
- otcinfra2
=> Enable CRDs for kube-prometheus-stack across environments

playbooks/roles/gitea/templates/app.ini.j2
Security Enhancements
- Added REQUIRE_SIGNIN_VIEW = true to repository section to block anonymous access to repositories
- Added DEFAULT_PRIVATE = true to make all new repositories private by default
- Updated [service.explore] section to require authentication for browsing
- Added REQUIRE_SIGNIN_VIEW = true to API section for consistent authentication requirements
- Disabled push create options to prevent repository creation by unauthenticated users
Deprecation Fixes
- Replaced [oauth2].ENABLE with [oauth2].ENABLED
- Replaced [log].ENABLE_ACCESS_LOG with [log].logger.access.MODE
- Replaced [log].ROUTER with [log].logger.router.MODE
Updated mailer configuration:
- Replaced MAILER_TYPE with PROTOCOL
- Replaced HOST with SMTP_ADDR
- Removed IS_TLS_ENABLED in favor of PROTOCOL setting
=> Update Gitea Configuration to Enforce Authentication and Fix Deprecation Warnings

playbooks/roles/gitea/templates/app.ini.j2
- Updated router logging configuration to use logger.router.MODE
- Changed access logger level to Warn and specified access log file
- Modified mailer settings: replaced MAILER_TYPE with PROTOCOL and HOST with SMTP_ADDR
=> Gitea logging and mailer configuration

kubernetes/argocd-apps/system/grafana/values-otcinfra.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-de.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-nl.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcci.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml, kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra2.yaml, kubernetes/argocd-apps/system/victoria-metrics-auth/values-otcinfra.yaml, kubernetes/backstage/overlays/dev/kustomization.yaml, kubernetes/backstage/overlays/prod/kustomization.yaml, kubernetes/circle-partner-navigator/base/cpn-front-ingress.yaml, kubernetes/circle-partner-navigator/base/cpn-ingress.yaml, kubernetes/dep-track/overlays/prod/kustomization.yaml, kubernetes/docsportal/overlays/docsportal/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_archive/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_internal/ingress-oauth.yaml, kubernetes/docsportal/overlays/helpcenter_public/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_archive/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_beta/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_internal/kustomization.yaml, kubernetes/docsportal/overlays/helpcenter_swiss_public/kustomization.yaml, kubernetes/mcaptcha/base/ingress.yaml, kubernetes/umami/base/ingress.yaml, kubernetes/zuul/overlays/zuul_ci/kustomization.yaml, playbooks/templates/charts/argocd/argocd-values.yaml.j2
`Warning  CannotRegenerateKey  4m50s (x3 over 47h)  cert-manager-certificates-key-manager  User intervention required: existing private key in Secret "argocd-server-tls" does not match requirements on Certificate resource, mismatching fields: [spec.privateKey.size], but cert-manager cannot create new private key as the Certificate's .spec.privateKey.rotationPolicy is unset or set to Never. To allow cert-manager to create a new private key you can set .spec.privateKey.rotationPolicy to 'Always' (this will result in the private key being regenerated every time a cert is renewed)`
=> Add cert-manager annotation for private key rotation policy across ingresses

inventory/service/group_vars/k8s-controller.yaml, playbooks/templates/charts/argocd/argocd-values.yaml.j2
- Updated ArgoCD Helm chart version from 7.6.12 to 7.8.15 in k8s-controller.yaml.
- Added global domain configuration in argocd-values.yaml.j2 for improved domain management.
=> Update ArgoCD version and add global domain configuration

.github/dependabot.yml
Addapted `dependabot.yaml` for docker check on daily bases
closes #1254
=> 1254 - Addition of docker check of dependabot for system-config repository

doc/requirements.txt, kubernetes/argocd-apps/system/victoria-metrics-auth/values-otcinfra.yaml, kubernetes/argocd-apps/system/victoria-metrics-cluster/values-otcinfra.yaml
Bump the image tag for: 
- victoria-metrics-auth from v1.100.1 to v1.117.1 
- victoria-metrics-cluster from v1.116.0-cluster to v1.117.1-cluster
=> Update Victoria Metrics image tags to v1.117.1

kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml
1) Disable NodeClockNotSynchronising alert for 2 worker nodes from otcinfra cluster via hardcoded IPs
=> Test disabling for 2 worker nodes

kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml
1) Disabling NodeClockNotSynchronising alert for .21.* subnet with worker nodes
=> Disable node clock sync for 21 subnet
