opentelekomcloud-infra/system-config

playbooks/templates/clouds/bridge_all_clouds.yaml.j2
playbooks/templates/clouds/bridge_kube_config.yaml.j2
playbooks/templates/clouds/nodepool_clouds.yaml.j2
playbooks/zuul/run-base.yaml
playbooks/zuul/templates/group_vars/control-plane-clouds.yaml.j2
playbooks/zuul/templates/group_vars/nodepool.yaml.j2
playbooks/zuul/templates/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml.j2
testinfra/test_bridge.py
zuul.d/project.yaml

Enable more (periodic) jobs and add some additional inventory data

Run periodic jobs

---

inventory/base/group_vars/all.yaml
inventory/base/hosts.yaml
playbooks/base.yaml
playbooks/roles/statsd/templates/config.js.j2
testinfra/test_statsd.py

Validate statsd service is properly running

---

inventory/service/groups.yaml

manually tested the playbook on web3

added web3 to alerta group

---

playbooks/templates/grafana/apimon/kpi.yaml.j2
playbooks/templates/grafana/apimon/network.yaml.j2

Changes already deployed into testing folder

add csm ping panels to network dashboard

---

inventory/service/group_vars/apimon.yaml

Switch main prod apimon to new isolated domain

new domain

---

inventory/service/group_vars/cloud-launcher.yaml
inventory/service/groups.yaml
inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
playbooks/cloud-loadbalancer.yaml
playbooks/roles/cloud_loadbalancer/defaults/main.yaml
playbooks/roles/cloud_loadbalancer/tasks/build.yaml
playbooks/roles/cloud_loadbalancer/tasks/destroy.yaml
playbooks/roles/cloud_loadbalancer/tasks/main.yaml
playbooks/roles/cloud_loadbalancer_cert/defaults/main.yaml
playbooks/roles/cloud_loadbalancer_cert/tasks/build.yaml
playbooks/roles/cloud_loadbalancer_cert/tasks/destroy.yaml
playbooks/roles/cloud_loadbalancer_cert/tasks/main.yaml
playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml
playbooks/templates/clouds/bridge_all_clouds.yaml.j2
playbooks/zuul/templates/group_vars/control-plane-clouds.yaml.j2

Requires change in the modules, but since is currently not invoked automatically can be merged.
Soft-depends-on: https://github.com/opentelekomcloud/ansible-collection-cloud/pull/104

Add cloud LB handling

---

playbooks/dashboards.yaml
playbooks/dashboards_local.yaml
playbooks/templates/grafana/apimon/block_storage.yaml.j2
playbooks/templates/grafana/apimon/compute.yaml.j2
playbooks/templates/grafana/apimon/storage.yaml.j2

Deployed currently under testingApimon folder

Add storage dashboard and metadata panel to compute

---

playbooks/roles/gitcontrol/files/github_api.py
playbooks/roles/gitcontrol/tasks/main.yml
playbooks/roles/gitcontrol/tasks/teams-present.yaml

currently added endpoint for invitation to orgs
and teams management

members and teams endpoints

---

inventory/service/group_vars/apimon.yaml

- Optimize haproxy config
- Enable coreos test on apimon NL

Enable scenario2c_coreos scenario for NL

---

inventory/service/group_vars/all.yaml
inventory/service/group_vars/cloud-launcher.yaml
inventory/service/group_vars/database-launcher.yaml
inventory/service/groups.yaml
playbooks/cloud-identity.yaml
playbooks/cloud-rds.yaml
playbooks/roles/cloud_rds/defaults/main.yaml
playbooks/roles/cloud_rds/tasks/destroy.yaml
playbooks/roles/cloud_rds/tasks/main.yaml
playbooks/roles/cloud_rds/tasks/provision.yaml
playbooks/roles/db_pg/README.rst
playbooks/roles/db_pg/tasks/db.yaml
playbooks/roles/db_pg/tasks/main.yaml
playbooks/roles/db_pg/tasks/user.yaml
playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml
playbooks/service-database.yaml
playbooks/templates/clouds/bridge_all_clouds.yaml.j2

before we start deploying more things to the new cloud we add it into the inventory.
Using this cloud start managing Databases

Add new infra cloud

---

inventory/service/group_vars/cloud-launcher.yaml
inventory/service/group_vars/proxy.yaml

- switch IP address in the haproxy
- fix wrong project name in the vpcp mgmt

Complete migration of the k8 cluster

---

inventory/service/group_vars/carbonapi.yaml

- Deploy matrix into k8
- Switch to quay image for carbonapi

Hotfix for carbonapi

---

playbooks/roles/alerta_k8s/defaults/main.yaml
playbooks/roles/alerta_k8s/tasks/main.yaml
playbooks/roles/grafana_k8s/defaults/main.yaml
playbooks/roles/grafana_k8s/tasks/main.yaml

Made state variable, default in role defaults/main.yaml to present
Added apply=yes for tasks in roles to apply k8s manifests

Added namespace management to alerta/grafana roles

---

inventory/service/group_vars/otc.yaml
playbooks/roles/base/unbound/handlers/main.yaml
playbooks/roles/base/unbound/tasks/main.yaml
playbooks/roles/base/unbound/templates/unbound.confd.conf.j2

in order to deploy zookeeper we need to ensure dns resolution works like
ZK expects it (private zones are supported)

Alter unbound configuration

---

inventory/base/hosts.yaml
inventory/service/group_vars/zuul-zookeeper.yaml
inventory/service/groups.yaml
inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/zk1.zuul.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/zk2.zuul.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/zk3.zuul.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/x509_cert/tasks/cert.yaml
playbooks/roles/zookeeper/README.rst
playbooks/roles/zookeeper/defaults/main.yaml
playbooks/roles/zookeeper/handlers/main.yaml
playbooks/roles/zookeeper/tasks/main.yaml
playbooks/roles/zookeeper/templates/env.j2
playbooks/roles/zookeeper/templates/zookeeper.service.j2
playbooks/roles/zookeeper/vars/Debian.yaml
playbooks/roles/zookeeper/vars/RedHat.yaml
playbooks/service-zookeeper.yaml
playbooks/zuul/templates/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml.j2
testinfra/test_zookeeper.py
zuul.d/infra-prod.yaml
zuul.d/project.yaml
zuul.d/system-config-run.yaml

- extend inventory with ZK hosts
- extend X509 role to support different PK format (for ZK)
- deploy ZK cluster in a container
Depends-On: https://github.com/opentelekomcloud-infra/system-config/pull/185

Add zookeeper deployment

---

inventory/service/group_vars/k8s-controller.yaml
inventory/service/group_vars/proxy.yaml
inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy2.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/document_hosting_k8s/tasks/main.yaml
playbooks/roles/document_hosting_k8s/templates/nginx-site.conf.j2
playbooks/roles/haproxy/tasks/main.yaml

- deploy main instance of doc portal
- adapt inventory to get SSL on the bridge, but use this cert in k8
- adapt nginx template to be matching reality more

Start docportal

---

playbooks/roles/document_hosting_k8s/templates/nginx-site.conf.j2

Add required rules into the nginx config

Update doc hosting nginx config

---

playbooks/roles/document_hosting_k8s/templates/nginx-site.conf.j2

- Fix few typos in the nginx template

fix typos in nginx template

---

inventory/service/group_vars/apimon.yaml
playbooks/roles/apimon_k8s/tasks/main.yaml
playbooks/service-apimon-epmon.yaml
playbooks/service-apimon-executor.yaml
playbooks/service-apimon-k8s.yaml
playbooks/service-apimon-scheduler.yaml
playbooks/zuul/templates/group_vars/apimon-clouds.yaml.j2
playbooks/zuul/templates/group_vars/apimon.yaml.j2
testinfra/test_epmon.py

- add possibility to use different tag on different instances
- deploy change_24_latest to stg instance

Update apimon stg to change_24

---

doc/source/proxy.rst
doc/source/systems.rst
playbooks/roles/haproxy/templates/haproxy.cfg.j2

- once we define acl for non https traffic we need a separate command to
do real redirect
- also add hsts header

Add proper https redirect

---

doc/source/gitcontrol.rst
doc/source/systems.rst
playbooks/install-ansible.yaml
zuul.d/infra-prod.yaml
zuul.d/system-config-run.yaml

- install new collection to manage github (switch in a followup)
- add gitcontrol document

Map gitcontrol collection to the bridge

---

playbooks/manage-github.yaml

- complete switch of the gitstyring project to ansible collection

Switch manage-github to use collection

---

docker/haproxy-statsd/haproxy-statsd.py
playbooks/monitor_haproxy.yaml
playbooks/roles/haproxy_monitor/README.rst
playbooks/roles/haproxy_monitor/tasks/backend.yaml
playbooks/roles/haproxy_monitor/tasks/frontend.yaml
playbooks/roles/haproxy_monitor/tasks/main.yaml
zuul.d/docker-images/haproxy-statsd.yaml
zuul.d/project.yaml

- report haproxy "status" gauges for the servers
- add playbook/role to watch haproxy backends/frontends and trigger
"reload" if something goes wrong

Haproxy recovery

---

inventory/service/group_vars/k8s-controller.yaml
playbooks/roles/octavia_proxy/tasks/k8s.yaml
playbooks/templates/octavia_proxy/octavia_proxy.conf.j2

- Implement octavia-proxy deployment
- Fix octavia deployment typos

Octavia-proxy deployment improvements

---

inventory/base/hosts.yaml
playbooks/roles/base/repos/files/sources.list.sid.x86_64
playbooks/roles/base/server/vars/Debian.yaml

first step integrating swift is to take hosts under inventory for base
job

Add swift hosts into inventory

---

inventory/service/host_vars/storage1.swift.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/storage2.swift.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/storage3.swift.eco.tsi-dev.otc-service.com.yaml

- fix deprecation warnign in ansible cfg
- fix typo in the sources.list.sid file
- Integrate swift configuration
- fix renamed vars in swift inventory

Fix renamed swift inventory vars

---

playbooks/roles/base/server/tasks/main.yaml
playbooks/roles/base/server/templates/logrotate.j2

instead of modifying logrotate.conf (what cause issues with system
updates) we should be putting our config part file under
/etc/logrotate.d/

Put logrotate conf.d file

---

playbooks/roles/zuul_k8s/tasks/zuul-executor.yaml
playbooks/roles/zuul_k8s/tasks/zuul-merger.yaml

certs must be 0400 (256 of k8 in dec form)

fix defaultMode for zuul k8 objects

---

playbooks/templates/grafana/apimon/_kpi_block_storage.yaml.j2
playbooks/templates/grafana/apimon/_kpi_cce.yaml.j2
playbooks/templates/grafana/apimon/_kpi_compute.yaml.j2
playbooks/templates/grafana/apimon/block_storage.yaml.j2
playbooks/templates/grafana/apimon/compute.yaml.j2
playbooks/templates/grafana/apimon/identity.yaml.j2
playbooks/templates/grafana/apimon/image.yaml.j2
playbooks/templates/grafana/apimon/macros.j2
playbooks/templates/grafana/apimon/network.yaml.j2
playbooks/templates/grafana/apimon/storage.yaml.j2

- add overall service max latency
- fix error runs query
- update to timeseries panel for some dashboards
- add max latency per api to service dashboards

Extend dahboard

---

playbooks/templates/grafana/apimon/identity.yaml.j2
playbooks/templates/grafana/apimon/network.yaml.j2

- switch all panels on network dashboard to type timeseries
- fix service_max_latency macro in identity

Further adapt dashboards

---

inventory/service/group_vars/grafana.yaml
inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/grafana/tasks/k8s.yaml
playbooks/roles/grafana/templates/grafana-secret.yaml.j2

- modification of grafana role - prerequisites for running grafana without ldap
- cert for grafana-eco + grafana-eco instance in inventory

grafana-eco instance + prereqs

---

inventory/service/group_vars/zuul.yaml
playbooks/roles/zuul_k8s/tasks/zuul-executor.yaml

- update to newer zuul version
- raise limits of the executor in an attempt to solve periodic problems

Scale up zuul executor limits

---

inventory/service/group_vars/cloud-launcher.yaml
inventory/service/group_vars/k8s-controller.yaml
playbooks/roles/cloud_loadbalancer/tasks/build.yaml
playbooks/roles/swift_proxy/defaults/main.yaml
playbooks/roles/swift_proxy/tasks/k8s.yaml
playbooks/service-swift-proxy.yaml

- in order to publish securely some of the artifacts we need to deploy
swift-proxy. Do this as role and not helm chart due to its simplicity
- fix LB setup (do proper unset and fix checks not for cases when we
have different LB setups in inventory)

Add swift_proxy deployment

---

tools/update_tag.py

Add script which updates `image_tag` in concrete `key`
Refers to: #220

Add `update_tag.py` script

---

inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml

Generate vault cert on the bridge

---

inventory/service/group_vars/zuul.yaml
playbooks/roles/zuul_k8s/tasks/zuul-executor.yaml
playbooks/roles/zuul_k8s/templates/zuul.conf.j2

- install additional py packages for ansible in zuul
- update zuul to 4.10.4

Manage zuul runtime on start

---

playbooks/roles/swift/defaults/main.yaml

- update py dependencies for the swift installation

Update package versions on swift

---

inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml

We want a global name for the vault cert

Modify vault cert

---

playbooks/zuul/run-production-playbook.yaml

Reverts opentelekomcloud-infra/system-config#361

Revert "De-duplicate bridge registering"

---

inventory/base/hosts.yaml
inventory/service/group_vars/cloud-launcher.yaml
inventory/service/groups.yaml
inventory/service/host_vars/graphite3.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/vault1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/vault2.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/vault3.eco.tsi-dev.otc-service.com.yaml
playbooks/cloud-hosts.yaml
playbooks/roles/acme_create_certs/handlers/reload-vault.yaml
playbooks/roles/acme_create_certs/tasks/main.yaml
playbooks/roles/hashivault/handlers/main.yaml
playbooks/roles/hashivault/tasks/Debian.yaml
playbooks/roles/hashivault/tasks/main.yaml
playbooks/roles/hashivault/templates/vault.hcl.j2
playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml

- add dedicated vault hosts
- fix various vault issues

Improve vault installation

---

playbooks/cloud-cce.yaml
playbooks/cloud-hosts.yaml
playbooks/cloud-identity.yaml
playbooks/cloud-loadbalancer.yaml
playbooks/cloud-networks.yaml
playbooks/cloud-rds.yaml
playbooks/cloud-security-groups.yaml
playbooks/cloud-vpcp.yaml
playbooks/install-helm-chart.yaml
playbooks/service-alerta.yaml
playbooks/service-apimon-k8s.yaml
playbooks/service-database.yaml
playbooks/service-docs.yaml
playbooks/service-grafana.yaml
playbooks/service-graphite.yaml
playbooks/service-loki.yaml
playbooks/service-matrix.yaml
playbooks/service-maubot.yaml
playbooks/service-octavia-proxy.yaml
playbooks/service-swift-proxy.yaml
playbooks/service-zookeeper.yaml
playbooks/service-zuul-k8s.yaml

with the switch to automation user some playbooks fail. Explicitly use
"become: true" cause missing stuff is available only for root.

Become root in the playbooks

---

playbooks/base.yaml
playbooks/roles/base/repos/tasks/main.yaml
playbooks/roles/base/server/tasks/RedHat.yaml
playbooks/roles/base/server/tasks/main.yaml
playbooks/roles/base/unbound/tasks/main.yaml

- Replace executor2 host
- Update base roles to be applied widely

Update base roles

---

inventory/service/host_vars/bastion.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/base/server/defaults/main.yaml
playbooks/roles/base/server/tasks/main.yaml
playbooks/roles/base/server/templates/sshd_config.j2

Apply recommendations and requirements from DT PSA security requirement for
the SSH (3.04)

Tune ssh config to the DT security requirements

---

inventory/service/group_vars/k8s-controller.yaml
playbooks/roles/zookeeper/defaults/main.yaml
playbooks/roles/zookeeper/tasks/k8_certificates.yaml
playbooks/roles/zookeeper/tasks/k8s.yaml
playbooks/roles/zookeeper/templates/k8s_config.yaml.j2
playbooks/roles/zookeeper/templates/statefulset.yaml.j2
playbooks/roles/zookeeper/templates/vault-agent-config.yaml.j2
playbooks/service-zookeeper.yaml
playbooks/zuul/templates/group_vars/k8s-controller.yaml.j2

Extend zookeeper role to support k8

Add support for zookeeper@k8

---

zuul.d/infra-prod.yaml
zuul.d/project.yaml

Refactor the infra-prod jobs to specify dependencies so they can run
in parallel.

Refactor infra-prod jobs for parallel running

---

inventory/service/group_vars/zuul.yaml
playbooks/roles/zuul_k8s/tasks/main.yaml
playbooks/roles/zuul_k8s/tasks/nodepool.yaml
playbooks/roles/zuul_k8s/tasks/zuul-scheduler.yaml
playbooks/roles/zuul_k8s/tasks/zuul-web.yaml
playbooks/roles/zuul_k8s/templates/zuul.conf.hcl.j2

- update zuul version
- update used vault version
- make zuul-config repo available in nodepool
- read tenant config from zuul-config shared volume
- update probes in zuul-web

Update Zuul to 4.11

---

inventory/service/group_vars/all.yaml

Update Grafana to 8.3.3 version.

Update Grafana to 8.3.3

---

playbooks/roles/x509_vault/tasks/cert.yaml
playbooks/roles/zookeeper/tasks/k8s.yaml
playbooks/roles/zookeeper/templates/k8s_config.yaml.j2
playbooks/roles/zuul_k8s/tasks/main.yaml
playbooks/roles/zuul_k8s/tasks/zuul-config.yaml
playbooks/roles/zuul_k8s/templates/vault-agent-config.hcl.j2
playbooks/roles/zuul_k8s/templates/zuul.conf.hcl.j2
playbooks/templates/clouds/nodepool_clouds.hcl.j2

- switch to using [% %] in hcl templates rather then in jinja
- get rid of secret/data prefixes in vault data to improve portability
of changing secret storages

Improve hcl template handling

---

playbooks/roles/hashivault/defaults/main.yaml
playbooks/roles/hashivault/tasks/main.yaml
playbooks/roles/hashivault/templates/vault.hcl.j2
playbooks/service-vault.yaml

- add vault plugins
- fix api address (for plugins)

Add support for adding vault plugins

---

inventory/service/group_vars/vault.yaml

- Add support for adding vault plugins
- Add vault plugins

Add vault plugins

---

inventory/service/groups.yaml
playbooks/configure-vault.yaml
playbooks/roles/configure_vault/tasks/approle.yaml
playbooks/roles/configure_vault/tasks/main.yaml
playbooks/roles/configure_vault/tasks/policy.yaml
playbooks/roles/install-ansible/files/inventory_plugins/test-fixtures/results.yaml

- Add support for configuring vault policies and approles
- at the moment there is no job doing that. This will be added once
implementation is complete

Add vault configuration playbook

---

playbooks/bootstrap-vault.yaml
playbooks/configure-vault.yaml
playbooks/roles/configure_vault/tasks/auth.yaml
playbooks/roles/configure_vault/tasks/k8auth.yaml
playbooks/roles/configure_vault/tasks/k8role.yaml
playbooks/roles/configure_vault/tasks/kubernetes.yaml
playbooks/roles/configure_vault/tasks/main.yaml
playbooks/roles/configure_vault/tasks/secret_engine.yaml

- add further config entities for vault
- add bootstrap-vault playbook which takes instance name and token to
have possibilitiy to use root token for initial bootstraping of all
requirements.

Extend vault configuration

---

playbooks/templates/clouds/bridge_kube_config.yaml.j2
playbooks/zuul/templates/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml.j2
testinfra/test_bridge.py

put secret part of the inventory underneath "secrets" key which we can
populate from vault or from some other place easier in one lookup.

Adapt k8 config to get data from improved inventory

---

playbooks/roles/install-ansible/files/lookup_plugins/vault_cloud_config.py
playbooks/roles/install-ansible/tasks/main.yaml
playbooks/roles/install-ansible/templates/ansible.cfg.j2

Implement ansible lookup plugin for ease of the cloud connections
configuration.

Add vault_cloud_config ansible lookup plugin

---

playbooks/roles/install-ansible/files/lookup_plugins/vault_cloud_config.py

- add reporting when user_path is wrong
- add conversion of additional params to int (when look like)

Update vault_cloud_config plugin

---

playbooks/roles/zookeeper/templates/k8s_config.yaml.j2
playbooks/roles/zuul_k8s/tasks/main.yaml
playbooks/roles/zuul_k8s/tasks/zuul-executor.yaml
playbooks/roles/zuul_k8s/templates/vault-agent-config.hcl.j2
playbooks/roles/zuul_k8s/templates/zuul-base-vault-agent-config.hcl.j2

- correct token_path variable in vault-agent config
- add zuul global variables support

Improve K8 vault integration

---

playbooks/roles/zuul_k8s/tasks/nodepool.yaml
playbooks/roles/zuul_k8s/tasks/zuul-client.yaml

We do not use it anymore and the volume is dropped.

Drop zk-certs volume for nodepool

---

inventory/base/hosts.yaml
inventory/service/groups.yaml
inventory/service/host_vars/executor1.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/executor3.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/executor4.apimon.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/cloud_host/tasks/construct_volumes_idlist.yaml
playbooks/roles/cloud_host/tasks/provision.yaml

- changed cloud_host role to have support for userdata and data volumes
- cloud host variables for executor1

cloud host data disk

---

inventory/service/group_vars/apimon.yaml
playbooks/roles/cloudmon_plugin/templates/plugin.service.j2

- fix wrong statsd IP address for cloudmon
- fix loglevel var name and reduce stop timeout

Fix wrong statsd for cloudmon@vc

---

inventory/service/group_vars/k8s-controller.yaml
inventory/service/group_vars/proxy.yaml
inventory/service/host_vars/bridge.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy2.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/opensearch/tasks/main.yml
playbooks/templates/charts/opensearch/opensearch-otcinfra-values.yaml.j2
playbooks/templates/charts/opensearch/opensearch-stg-dashboard-otcinfra2-values.yaml.j2
playbooks/templates/charts/opensearch/opensearch-stg-otcinfra2-values.yaml.j2

Get all config values from variables directly including securityConfig.

Manage opensearch config differently

---

inventory/service/group_vars/all.yaml
inventory/service/group_vars/apimon.yaml

change config to cloudmon-plugin-lb v2

Update cloudmon-lb plugin

---

inventory/base/hosts.yaml
inventory/service/group_vars/all.yaml
inventory/service/host_vars/executor1.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/executor3.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/executor4.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/hybrid.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/preprod.apimon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/proxy2.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/scheduler1.apimon.eco.tsi-dev.otc-service.com.yaml

- additional cloud_hosts
- further hosts

Host provisioning - further hosts

---

playbooks/roles/zookeeper/templates/statefulset.yaml.j2

we forgot to set autopurge interval for the k8 case

Set zookeeper_autopurge_interval

---

inventory/service/host_vars/graphite1.eco.tsi-dev.otc-service.com.yaml

- reduce zuul metrics retention policies
- reduce default retention policies

Update graphite retention policies on graphite1

---

playbooks/zuul/run-base.yaml

Apply change from https://review.opendev.org/c/opendev/system-config/+/831465

zuul run-base: make sure we catch failures when teeing to logs

---

playbooks/roles/zookeeper/tasks/k8s.yaml
playbooks/roles/zookeeper/templates/statefulset.yaml.j2

- fix ZK PodDistruptionBudget
- add zk ss node anti-affinity

Improve k8 handling of ZK

---

playbooks/roles/zookeeper/tasks/k8s.yaml
playbooks/roles/zookeeper/templates/statefulset.yaml.j2

- make zk labels consistent
- fix anti-affinity to rely on proper labels

Fix labels of ZK k8

---

inventory/service/group_vars/all.yaml
playbooks/templates/cloudmon/metrics-config.yaml.j2

fix metric names in the cloudmon-metrics expressions and update to
newest cloudmon-metrics image.

Fix few expressions in cloudmon-metrics

---

inventory/service/group_vars/cloud-launcher.yaml
playbooks/cloud-dns.yaml
playbooks/cloud-networks.yaml
playbooks/cloud-security-groups.yaml
playbooks/roles/cloud_dns/tasks/build.yaml
playbooks/roles/cloud_dns/tasks/destroy.yaml
playbooks/roles/cloud_dns/tasks/main.yaml
playbooks/roles/cloud_natgw/tasks/destroy.yaml
playbooks/roles/cloud_natgw/tasks/main.yaml
playbooks/roles/cloud_natgw/tasks/provision.yaml
playbooks/roles/cloud_net/tasks/destroy.yaml
playbooks/roles/cloud_net/tasks/destroy_net.yaml
playbooks/roles/cloud_net/tasks/main.yaml
playbooks/roles/cloud_net/tasks/net.yaml
playbooks/roles/cloud_net/tasks/provision.yaml
playbooks/roles/cloud_net/tasks/subnet.yaml
playbooks/roles/cloud_sg/tasks/destroy.yaml
playbooks/roles/cloud_sg/tasks/main.yaml
playbooks/roles/cloud_sg/tasks/provision.yaml

moved :
- cloud-dns
- cloud-networks (routers/subnets/nets/natgws)
- cloud-security-groups

Cloud provisioning to use openstack vault credentials

---

playbooks/roles/gitea/templates/env.j2
playbooks/roles/gitea/templates/gitea.service.j2
zuul.d/infra-prod.yaml
zuul.d/project.yaml

Fix last issue with gitea deployment and enable automatic jobs.

Enable gitea job

---

playbooks/templates/docs_hosting/nginx-internal.conf.j2

Apply same schema for the internal docsportal as for the external one.

Update internal docsportal nginx config

---

docker/zuul/Dockerfile

https://review.opendev.org/c/zuul/zuul/+/850941

New Zuul base change

---

inventory/service/group_vars/zuul.yaml

- start building zuul image from another change
- switch to new build of zuul and nodepool

zuul gitea

---

inventory/service/group_vars/gitea.yaml

upgrade gitea and place version to the inventory explicitly (override role defaults)

upgrade gitea to 1.18.0

---

inventory/service/host_vars/storage6.swift.eco.tsi-dev.otc-service.com.yaml
playbooks/distribute-swift-rings.yaml
playbooks/roles/cloud_host/tasks/provision.yaml

- replace storage6 swift server with c4.2xlarge.2 flavor and single SAS disk
- add playbook to distribute swift ring files

Replace storage6.swift

---

inventory/service/group_vars/gitea.yaml

https://github.com/go-gitea/gitea/issues/22380

Rollback of gitea version due to bug on show more files

---

inventory/base/hosts.yaml
inventory/service/group_vars/cloud-launcher.yaml
inventory/service/host_vars/hc1.eco.tsi-dev.otc-service.com.yaml

- switch to public ip for accessing host
- fix cloud-launcher inventory
- Allow zuul to connect to hc1

Fix some issues with failover host data

---

testinfra/test_keycloak.py
zuul.d/system-config-run.yaml

some jobs were not properly working cause they had no proper bridge in
the inventory

Fix test jobs

---

inventory/service/group_vars/k8s-controller.yaml
playbooks/roles/document_hosting_k8s/tasks/main.yaml
playbooks/roles/document_hosting_k8s/templates/deployment.yaml.j2
playbooks/templates/docs_hosting/archive.conf.j2
playbooks/templates/docs_hosting/fallback.conf.j2

- split HC into HC and HC-beta instances
- add fallback service

Add fallback pod and service for docsportal

---

inventory/service/group_vars/all.yaml
inventory/service/group_vars/k8s-controller.yaml
playbooks/templates/docs_hosting/nginx-internal.conf.j2
playbooks/templates/docs_hosting/nginx-public.conf.j2

- fix image links under developer
- Various hotfix changes
All of those applied locally, this is post logging of actions

Various hotfixes for HC go live

---

playbooks/templates/charts/loki/loki-values.yaml.j2

previous change missed one changed file required for upgrade of loki
chart

Fix loki chart installation

---

playbooks/roles/document_hosting_k8s/templates/deployment.yaml.j2

without resources specified for all of the containers HPA is failing to
calculate the load properly. Add minimal data.

Add HC sidecar resources

---

zuul.d/infra-prod.yaml

when we modify docs templates we need to actually deploy those changes

Deploy docs on changes to templates

---

inventory/service/group_vars/gitea.yaml

this change includes CVE fix and other important bugfix

update gitea to 1.18.2

---

inventory/service/group_vars/zuul.yaml

our change was rebased to contain 8.0.1 release

Upgrade Zuul to 8.0

---

playbooks/roles/gitea/templates/app.ini.j2

Now that the bug was fixed we can bring back amount of changed files on the PR page

Bring back amount of diff files on page in gitea

---

inventory/base/hosts.yaml
inventory/service/host_vars/storage3.swift.eco.tsi-dev.otc-service.com.yaml

https://github.com/opentelekomcloud-infra/system-config/issues/738

replace swift storage3

---

inventory/service/host_vars/storage4.swift.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/storage5.swift.eco.tsi-dev.otc-service.com.yaml

resolves https://github.com/opentelekomcloud-infra/system-config/issues/764

changed storage[4-5] flavors

---

playbooks/roles/acme_drop_txt_records/tasks/main.yaml
playbooks/roles/acme_install_txt_records/tasks/main.yaml

Add condition to let acme tasks to work with -limit argument

Enable host limit for SSL handling

---

inventory/base/hosts.yaml
inventory/service/groups.yaml
inventory/service/host_vars/graphite1.cloudmon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/graphite3.cloudmon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/worker-de-01.cloudmon.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/worker-nl-01.cloudmon.eco.tsi-dev.otc-service.com.yaml

- add 2 worker nodes
- fix typo in user-config for graphite nodes deployment

Add CloudMon worker nodes

---

playbooks/templates/charts/loki/loki-values.yaml.j2

200G are also not enough, go up to 300G

Increase PVC size for loki storage

---

kubernetes/zuul/components/nodepool-builder/statefulset.yaml
kubernetes/zuul/components/nodepool-launcher/deployment.yaml
kubernetes/zuul/overlays/zuul_ci/kustomization.yaml
kubernetes/zuul/overlays/zuul_ci/patch-nodepool.yaml

apply overlay patch to nodepool components differently to have proper
volumes added where expected.

fix(zuul): correct kustomize deployment of nodepool

---

inventory/service/group_vars/k8s-controller.yaml
kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml

- disable deployment of helpcenter-beta through SC and let Kustomize
overtake that
- fir configmap file names

feat(docs): Disable deployment of the hc-beta through SC

---

kubernetes/docsportal/overlays/helpcenter_beta/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml

Those fixes are included in the manual deploy of the docs-beta on hc-beta namespace

fix(docs): fix docs-beta deployment

---

kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_internal/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_public/kustomization.yaml

All new configs should also be added to kustomize

Add missing cm for kustomize

---

kubernetes/dep-track/base/kustomization.yaml

allow explicit update of depedencytrack

update: set dep-track explicitly to 4.8.0

---

kubernetes/zuul/components/zuul-scheduler/deployment.yaml
kubernetes/zuul/components/zuul-scheduler/kustomization.yaml
kubernetes/zuul/overlays/zuul_ci/configs/zuul.conf.hcl

- feat: convert zuul scheduler to deployment
- feat: convert zuul config to be generated by script

zuul scheduler changes

---

inventory/base/group_vars/all.yaml

rm kucerakk user

---

playbooks/roles/install-kubectl/defaults/main.yaml

I'm tired with that.
Need to update it finally.

upd kubectl

---

inventory/service/group_vars/cloud-launcher.yaml

- add 2 new projects for hc swiss and swiss int
- grant log_writer access to both new projects

add swiss envs

---

kubernetes/zuul/components/zookeeper/statefulset.yaml

fix zk autopurge

---

kubernetes/backstage/overlays/prod/kustomization.yaml

deploy support for GT bootstrap repo action

feat: update backstage image

---

kubernetes/backstage/overlays/prod/vault-agent.hcl

vault 1.13 requires those changes

feat: update backstage vault-agent config

---

kubernetes/docsportal/overlays/helpcenter_internal/kustomization.yaml

Do not expose service knowing its IP

make docs-int ingress internal

---

kubernetes/grafana-docs-monitoring/base/cronjob-fzswiss.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-ghswiss.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-lci.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-lciswiss.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-oi.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-oiswiss.yaml

1) adjust cron jobs for public cloud scripts
2) add new cronjobs for swiss

Grafana cronjobs

---

inventory/base/hosts.yaml
inventory/service/host_vars/gitea1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/gitea2.eco.tsi-dev.otc-service.com.yaml
playbooks/sync-gitea-data.yaml

gitea1 host update

---

kubernetes/zuul/components/restarter/job-restart-zuul-web.yaml

I hope this may fix issue after psql password change

restart zuul-web every 6 hours

---

inventory/service/group_vars/k8s-controller.yaml

6.15.2 latest available version

Update version for promtail helm chart 6.8.1-> 6.15.2

---

inventory/service/group_vars/k8s-controller.yaml

Update to the latest telegraf-ds version of chart

Update version for telegraf helm chart 1.1.0-> 1.1.17

---

kubernetes/docsportal/overlays/helpcenter_beta/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_beta/configs/redirect_maps/additional-resources
kubernetes/docsportal/overlays/helpcenter_internal/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_internal/configs/redirect_maps/additional-resources
kubernetes/docsportal/overlays/helpcenter_public/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_public/configs/redirect_maps/additional-resources
kubernetes/docsportal/overlays/helpcenter_swiss_beta/configs/redirect_maps/additional-resources
kubernetes/docsportal/overlays/helpcenter_swiss_internal/configs/redirect_maps/additional-resources
kubernetes/docsportal/overlays/helpcenter_swiss_public/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_swiss_public/configs/redirect_maps/additional-resources
playbooks/templates/docs_hosting/redirect_maps/redirect-additional-resources.map

fixes https://github.com/opentelekomcloud-docs/docsportal/issues/131

fix learmore redirect for docsportal

---

kubernetes/zuul/components/nodepool-builder/statefulset.yaml
kubernetes/zuul/components/nodepool-launcher/deployment.yaml
kubernetes/zuul/components/zookeeper/statefulset.yaml
kubernetes/zuul/components/zuul-client/deployment.yaml
kubernetes/zuul/components/zuul-config/deployment.yaml
kubernetes/zuul/components/zuul-executor/statefulset.yaml
kubernetes/zuul/components/zuul-merger/deployment.yaml
kubernetes/zuul/components/zuul-scheduler/deployment.yaml
kubernetes/zuul/components/zuul-web/deployment.yaml
kubernetes/zuul/overlays/zuul_ci/patch-nodepool.yaml
kubernetes/zuul/overlays/zuul_ci/patch-zuul-executor.yaml
kubernetes/zuul/overlays/zuul_ci/patch-zuul.yaml

Fix alerts with CPU throttling;
Increse nodepool-builder request for memory due OOMKilled restart

Fix alerts with CPU throttling; Change limits/requests according best practices;

---

zuul.d/infra-prod.yaml

Increase timeout from 30 to 45 for helm apply zuul job

---

inventory/service/host_vars/vault1.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/vault2.eco.tsi-dev.otc-service.com.yaml
inventory/service/host_vars/vault3.eco.tsi-dev.otc-service.com.yaml
playbooks/roles/hashivault/templates/vault.hcl.j2
playbooks/templates/charts/prometheus/prometheus-otcinfra-values.yaml.j2

Add telemetry config to hashivault role; update vault hostvars; add job for prometheus vault

Add monitoring for vault cluster

---

zuul.d/infra-prod.yaml

Following 
https://zuul-ci.org/docs/zuul/latest/config/job.html#attr-job.files and 
https://opendev.org/openstack/project-config/src/branch/master/zuul.d/jobs.yaml#L267

Adding correct format for files regexp

---

kubernetes/circle-partner-navigator/overlays/prod/kustomization.yaml

Switched to new tag for CPN-Backend.
Gating scheduled for 9-10am 07.02.

CPN Backend Update

---

inventory/base/hosts.yaml
inventory/service/group_vars/proxy.yaml
inventory/service/groups.yaml
playbooks/zuul/templates/gate-groups.yaml.j2

executor2.apimon.eco.tsi-dev.otc-service.com
graphite1.apimon.eco.tsi-dev.otc-service.com
web3.eco.tsi-dev.otc-service.com

Remove 3 stale hosts from inventory and vars

---

kubernetes/circle-partner-navigator/base/front-deploy.yaml
kubernetes/circle-partner-navigator/overlays/prod/cpn-front-nginx.conf
kubernetes/circle-partner-navigator/overlays/prod/kustomization.yaml

add pretty simple nginx config for cpn frontend to avoid 404 for local pages

nginx config for cpn front

---

kubernetes/grafana-docs-monitoring/base/cronjob-scheduler.yaml
kubernetes/grafana-docs-monitoring/base/kustomization.yaml
kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

1) Add cronjob yaml for scheduler.py
2) Fix kustomization

Add scheduler cronjob

---

kubernetes/grafana-docs-monitoring/overlays/prod/vault-agent.hcl

New variable for gdm

---

kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

1) New release tag 0.1.15 to implement changes

New release tag

---

kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

1) Add new release tag to implement changes from https://github.com/opentelekomcloud-infra/grafana-docs-monitoring/pull/57

new release 0.1.17

---

kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

gdm release 0.1.19

---

kubernetes/docsportal/overlays/helpcenter_internal/components/oauth-proxy/deployment.yaml
kubernetes/docsportal/overlays/helpcenter_internal/components/oauth-proxy/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_internal/components/oauth-proxy/service.yaml
kubernetes/docsportal/overlays/helpcenter_internal/components/oauth-proxy/vault-agent.hcl
kubernetes/docsportal/overlays/helpcenter_internal/components/redis/deployment.yaml
kubernetes/docsportal/overlays/helpcenter_internal/components/redis/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_internal/components/redis/service.yaml
kubernetes/docsportal/overlays/helpcenter_internal/ingress-oauth.yaml
kubernetes/docsportal/overlays/helpcenter_internal/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_internal/sa.yaml

deployed now at https://docs.otctest.t-systems.com
added another ingress to avoid conflicts with current docs-int

added oauth proxy to helpcenter-int

---

kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

New release 0.1.20

---

inventory/service/group_vars/apimon.yaml

enabled OBS test for all regions

enabled obs test for all regions

---

kubernetes/docsportal/overlays/helpcenter_public/configs/redirect_maps/additional-resources

https://github.com/opentelekomcloud-docs/docsportal/issues/186

Small redirection fix

---

kubernetes/grafana-docs-monitoring/base/cronjob-1-servicesdict.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-2-gt.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-3-gh.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-4-fz.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-5-oi.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-6-lci.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-7-rch.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-8-ei.yaml
kubernetes/grafana-docs-monitoring/base/cronjob-9-scheduler.yaml
kubernetes/grafana-docs-monitoring/base/kustomization.yaml
kubernetes/grafana-docs-monitoring/overlays/prod/kustomization.yaml

1) New schedule for cronjobs
2) Refactored file names for better handling
3) Fix for quite infinite loop

New release 0.1.22

---

kubernetes/docsportal/overlays/helpcenter_internal/configs/redirect_maps/additional-resources

to avoid some broken links on nested docsportal URI page

adding docsportal redirection to main page

---

inventory/base/group_vars/all.yaml

Add Sergei Martynov's ssh pub key for bridge access

Sergei Martynov's ssh key

---

kubernetes/docsportal/overlays/helpcenter_internal/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_swiss_beta/configs/nginx-site.conf
kubernetes/docsportal/overlays/helpcenter_swiss_internal/configs/nginx-site.conf

adding robots.txt to other non relevenat portal to avoid

---

inventory/service/group_vars/apimon.yaml

Change RDS scenario from scenario20_rds to scenario44_rds_instance as old one is obsolete.

Change RDS scenario from scenario20_rds to scenario44_rds_instance

---

kubernetes/argocd-apps/system/victoria-metrics-cluster/values-otcinfra.yaml

victoria metrics insert crashlooping with oom

Victoria metrics insert mem increase

---

kubernetes/eyes-on-docs/base/cronjob-1-servicesdict.yaml
kubernetes/eyes-on-docs/base/cronjob-2-gt.yaml
kubernetes/eyes-on-docs/base/cronjob-3-gh.yaml
kubernetes/eyes-on-docs/base/cronjob-4-fz.yaml
kubernetes/eyes-on-docs/base/cronjob-5-oi.yaml
kubernetes/eyes-on-docs/base/cronjob-6-lci.yaml
kubernetes/eyes-on-docs/base/cronjob-7-rch.yaml
kubernetes/eyes-on-docs/base/cronjob-8-ei.yaml
kubernetes/eyes-on-docs/base/cronjob-9-scheduler.yaml

1) Change image name case from kebab to snake

Correct case for image name

---

playbooks/roles/install-helm/defaults/main.yaml

updating helm to lastest version

update helm to 3.16.2

---

inventory/service/group_vars/gitea.yaml
playbooks/roles/gitea/defaults/main.yaml

1) Add new release version 1.22.3

Gitea upgrade to 1.22.3

---

kubernetes/umami/base/deploy.yaml
kubernetes/umami/base/ingress.yaml
kubernetes/umami/base/kustomization.yaml
kubernetes/umami/base/sa.yaml
kubernetes/umami/base/service.yaml
kubernetes/umami/overlays/analytics/kustomization.yaml
kubernetes/umami/overlays/analytics/vault-agent.hcl

initial deployment of umami analytics service.
publicly available at:
https://analytics.otc-service.com

add deploy umami

---

kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

1) New Eyes-on-Docs release 0.1.30

New EoD release 0.1.30

---

docker/zuul/Dockerfile

1) Zuul version 9.5.0
2) python-builder:3.11-bookworm
3) node:16-bookworm
4) OpenShift client 4.11.20

Upgrade Zuul to latest

---

inventory/base/group_vars/all.yaml

new key for yustina

---

inventory/service/group_vars/gitea.yaml
playbooks/roles/gitea/defaults/main.yaml

Gitea upgrade to 1.22.6

---

kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

1) Eyes-on-Docs release 0.1.31

EoD release 0.1.31

---

kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-de.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-nl.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcci.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra2.yaml

[monitoring] Empty prom selectors to match all ServiceMonitors

---

kubernetes/argocd-apps/bootstrap/app-of-apps/infrastructure.yaml
kubernetes/argocd-apps/system/cert-exporter/Chart.yaml
kubernetes/argocd-apps/system/cert-exporter/values.yaml

add cert-exporter to argocd apps

---

kubernetes/eyes-on-docs/base/cronjob-10-huawei.yaml
kubernetes/eyes-on-docs/base/kustomization.yaml
kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

1) Add new script eod-10-huawei scheduler

Eyes-on-Docs release 0.1.32

---

kubernetes/eyes-on-docs/base/cronjob-10-huawei.yaml

Eyes-on-Docs release 0.1.32 fix

---

kubernetes/eyes-on-docs/base/cronjob-10-huawei.yaml

Fix job name

---

kubernetes/argocd-apps/system/grafana/values-otcinfra.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-de.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-cloudmon-nl.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcci.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra2.yaml
kubernetes/argocd-apps/system/victoria-metrics-auth/values-otcinfra.yaml
kubernetes/backstage/overlays/dev/kustomization.yaml
kubernetes/backstage/overlays/prod/kustomization.yaml
kubernetes/circle-partner-navigator/base/cpn-front-ingress.yaml
kubernetes/circle-partner-navigator/base/cpn-ingress.yaml
kubernetes/dep-track/overlays/prod/kustomization.yaml
kubernetes/docsportal/overlays/docsportal/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_archive/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_beta/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_internal/ingress-oauth.yaml
kubernetes/docsportal/overlays/helpcenter_public/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_swiss_archive/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_swiss_beta/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_swiss_internal/kustomization.yaml
kubernetes/docsportal/overlays/helpcenter_swiss_public/kustomization.yaml
kubernetes/mcaptcha/base/ingress.yaml
kubernetes/umami/base/ingress.yaml
kubernetes/zuul/overlays/zuul_ci/kustomization.yaml
playbooks/templates/charts/argocd/argocd-values.yaml.j2

that enhances security across all public ingresses

Add cert-manager annotations for private key algorithm rsa and size 4096

---

kubernetes/eyes-on-docs/base/cronjob-11-hotc.yaml
kubernetes/eyes-on-docs/base/cronjob-12-filin.yaml
kubernetes/eyes-on-docs/base/kustomization.yaml
kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

1) New cronjob for eod11, eod12 scripts

Eyes-on-Docs release 0.1.33

---

kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

Eyes-on-Docs release 0.1.34

---

kubernetes/eyes-on-docs/overlays/prod/kustomization.yaml

1) New Eyes-on-Docs release 0.1.35

New Eyes-on-Docs release 0.1.35

---

inventory/service/group_vars/stackmon.yaml

1) Remove Olha Kashyrina's username from stackmon users

Remove old account

---

playbooks/roles/keycloak/defaults/main.yaml

update keycloak image to latest and keycloak postgres to latest patch of version 15

Update Keycloak and PostgreSQL images

---

inventory/service/group_vars/proxy.yaml
kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml
playbooks/roles/keycloak/templates/keycloak.service.j2

fixes for upgraded keycloak

---

.github/dependabot.yml

and update scheduling for Helm and Docker. 
Added daily checks at 09:00 for all specified ecosystems.

Enhance dependabot configuration to include GitHub Actions

---

kubernetes/zuul/components/nodepool-builder/statefulset.yaml
kubernetes/zuul/components/nodepool-launcher/deployment.yaml
kubernetes/zuul/components/zuul-client/deployment.yaml
kubernetes/zuul/components/zuul-config/deployment.yaml
kubernetes/zuul/components/zuul-executor/statefulset.yaml
kubernetes/zuul/components/zuul-merger/deployment.yaml
kubernetes/zuul/components/zuul-scheduler/deployment.yaml
kubernetes/zuul/components/zuul-web/deployment.yaml

its a workaround to fix failing mount sfs to euleros nodes

add temporary nodeselector for zuul components

---

inventory/service/group_vars/k8s-controller.yaml
playbooks/templates/charts/argocd/argocd-values.yaml.j2

upgrade helm chart to version: 8.0.13

Update ArgoCD Helm chart version and image tags to v3.0.5

---

inventory/service/group_vars/gitea.yaml
playbooks/roles/gitea/defaults/main.yaml

1) New Gitea release 1.24.0 SHA

New gitea release 1.24.0

---

kubernetes/argocd-apps/system/kube-prometheus-stack/values-otcinfra.yaml

1) New syntax for Alertmanager escape rules

New syntax for Alertmanager

---

kubernetes/kustomize/eyes-on-docs/overlays/prod/kustomization.yaml

1) New Eyes-on-Docs release 0.1.36

New Eyes-on-Docs release 0.1.36

---

.github/scripts/check_helm_dependencies.py

1) Fix script for work with double, single or no quotation marks at all

Handling quotation marks

---

playbooks/base.yaml
playbooks/roles/base/unbound/tasks/main.yaml
playbooks/roles/base/unbound/templates/interface.confd.conf.j2

Set up the unbound service to run only with ipv4 and on the localhost.

Unbound fix

---

.github/CODEOWNERS

1) Remove Vladimir Vshivkov from codowners for this repo

Remove Vova from codowners

---

kubernetes/kustomize/eyes-on-docs/overlays/prod/kustomization.yaml

1) Fix regex in eod_7
2) Change auth in eod_7 from basic to header

EoD release 0.1.37
